version: '3.1'

services:

  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017

  spring-server:
    image: gcr.io/k8s-minikube/storage-provisioner:v5
    ports:
      - 8080:8080
    links:
      - mongodb